import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MobileNavigationBar, Sidebar } from './components';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full md:min-h-full flex flex-col md:flex-row ">
        <section className="min-h-full md:flex hidden">
          <Sidebar />
        </section>
        <section className="flex flex-1 h-[90%] w-full md:min-h-full    ">
          {children}
        </section>
        <section className="flex md:hidden  w-full">
          <MobileNavigationBar />
        </section>
      </body>
    </html>
  );
}
